name: Aeon Reccomendation System Backend Workflow

on:
  # push:
  #   branches:
  #     - main  # Adjust the branch as necessary
  workflow_dispatch:
    inputs:
      change:
        description: "Details about the database change"
        required: false

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Log the trigger type
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "Triggered by a push to the repository."
          else
            echo "Triggered by a database change: ${{ github.event.inputs.change }}"
          fi

  model-deployment:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Data ingestion
        env:
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_USER:  ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASS:  ${{ secrets.POSTGRES_PASS }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        run: |
          python src/data_ingestion.py
      
      - name: Data validation
        run: |
          pytest test/test_data.py
      
      - name: Test Transformation functions
        run: | 
          pytest test/test_transformation.py
      
      - name: Data Transformation
        run: |
          python src\data_transformation.py
      
      - name: Generate objects
        run: |
          python src\vectorizer.py
      
      - name: Test objects
        run: |
          pytest test/test_objects.py
      
